### ISSUE TITLE
How to remove the shadow part when we press menu button

### ISSUE THREAD

**Issue by snehamadda** [qqmikey/kf_drawer#17]
There is a small shadow showing to the left side of the initial page. How can I remove that part?
Attached screenshot for reference.

![shadow](https://user-images.githubusercontent.com/62553206/99752038-92a63c00-2b09-11eb-86fe-4d1e787b1070.png)

**Comment by qqmikey** [comment]
```shadowOffset``` property on KFDrawer

**Comment by snehamadda** [comment]
I tried it, by adding it to the KF Drawer widget but it's not getting, can you provide me an example
