### ISSUE TITLE
Flutter upgrade Animation<BorderRadius?> with an exception

### ISSUE THREAD

**Issue by odproductor** [qqmikey/kf_drawer#23]
Hi! greetings!
I found a issue when i updagrde flutter:

`kf_drawer-1.2.0/lib/kf_drawer.dart:169:10: Error: A value of type 'Animation<BorderRadius?>' can't be assigned to a variable of type 'Animation<BorderRadius>' because 'BorderRadius?' is nullable and 'BorderRadius' isn't.`

and my project no works,
I appreciate your help, thanks!

**Comment by huanlirui** [comment]
我也遇到了！
I also encountered this problem

**Comment by vishnutvijay** [comment]
I have the same exception now

**Comment by kaitech-corp** [comment]
Same

**Comment by ramazantzr3433** [comment]
I have same problem but i did fix it. Just downgrade flutter 2.2.3 and it solves.

**Comment by qqmikey** [comment]
Release is coming...

**Comment by odproductor** [comment]
> Release is coming...

Great! Thanks

**Comment by Breaker-Chile** [comment]
La solución que hice fue copiar el paquete en un directorio local, solucionar el error (modificando el archivo .dart de la solución) que por null safety es el siguiente:

Dice: borderRadius: radiusAnimation.value,
Debe decir: borderRadius: radiusAnimation.value!,

y en el pubspec.yaml lo siguiente:

  kf_drawer:
    path: /Users/xxxxxxx/Proyects/kf_drawer

Greetings from Chile!
