### ISSUE TITLE
feature request screens tilted

### ISSUE THREAD

**Issue by ggichure** [qqmikey/kf_drawer#8]
i would love to achieve this using kf_drawer 
![sctilt](https://user-images.githubusercontent.com/31619962/68496754-19bca500-0264-11ea-8a63-878accb7353b.PNG)

**Comment by mubasshir** [comment]
+1
Hi, @ggichure  , did you find a solution for it?

**Comment by ggichure** [comment]
not yet, I focused on other stuff

**Comment by medyas** [comment]
@mubasshir @ggichure hey, i have created a new package with the support for both simple sliding and sliding with rotation. [Flutter Zoom Drawer](https://pub.dev/packages/flutter_zoom_drawer)

**Comment by ggichure** [comment]
@medyas  created a plugin with the above functionality
